laraschool/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//Admin Namespace
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\ChangePasswordController;
use App\Http\Controllers\Admin\UsersController;


//Controllers Namespace
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AgendaController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\PengumumanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Home
Route::get('/',[HomeController::class,'index']);
Route::get('/home',[HomeController::class,'index'])->name('home');
Route::get('/about',[HomeController::class,'about'])->name('about');
Route::get('/contact',[HomeController::class,'contact'])->name('contact');

//Artikel
Route::get('/artikel',[ArtikelController::class,'index'])->name('artikel');
Route::get('/artikel/search',[ArtikelController::class,'search'])->name('artikel.search');

Route::get('/artikel/{artikel:slug}',[ArtikelController::class,'show'])->name('artikel.show');

//Pengumuman
Route::get('/pengumuman',[PengumumanController::class,'index'])->name('pengumuman');
Route::get('/pengumuman/{pengumuman:slug}',[PengumumanController::class,'show'])->name('pengumuman.show');

//Admin
Route::group(['namespace' => 'Admin','prefix' => 'admin','middleware' => ['auth']],function(){
	Route::name('admin.')->group(function(){

		Route::get('/',[AdminController::class,'index'])->name('index');
		Route::get('/profile',[ProfileController::class,'index'])->name('profile.index');
		Route::get('/change-password',[ChangePasswordController::class,'index'])->name('change-password.index');

		//Resource Controller
		Route::resource('users','UsersController');
		Route::resource('pengumuman','PengumumanController');
		Route::resource('agenda','AgendaController');
		Route::resource('artikel','ArtikelController');
		Route::resource('kategori-artikel','KategoriArtikelController');
	});
});

laraschool/resources/views/admin/change-password.blade.php
@extends('layouts.backend.app',[
	'title' => 'Ubah Password',
	'contentTitle' => 'Ubah Password',
])
@section('content')
<x-alert></x-alert>
<div class="row">
	<x-card>
		<x-slot name="col">6</x-slot>
		<x-slot name="header">Ubah Password</x-slot>
		<form method="POST" action="{{ route('user-password.update') }}">
		@csrf
		@method('put')
		<div class="form-group">
			<label>Password Sekarang</label>
			<input type="password" class="form-control @error('current_password') is-invalid @enderror" name="current_password">
			@error('current_password')
		      <div class="invalid-feedback">
		          {{ $message }}
		       </div>
		    @enderror
		</div>
		<div class="form-group">
			<label>Password Baru</label>
			<input type="password" class="form-control @error('password') is-invalid @enderror" name="password">
			@error('password')
		      <div class="invalid-feedback">
		          {{ $message }}
		      </div>
		    @enderror
		</div>
		<div class="form-group">
			<button type="submit" class="btn btn-primary btn-sm">UPDATE</button>
		</div>
		</form>
	</x-card>

</div>
@stop

laraschool/resources/views/admin/index.blade.php
@extends('layouts.backend.app',[
	'title' => 'Dashboard',
	'contentTitle' => 'Dashboard',
])
@section('content')
<!-- Small boxes (Stat box) -->
<div class="row">
  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-info">
      <div class="inner">
        <h3>@count('users')</h3>

        <p>Admin</p>
      </div>
      <div class="icon">
        <i class="fas fa-user-tie"></i>
      </div>
      <a href="{{ route('admin.users.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-success">
      <div class="inner">
        <h3>@count('artikel')</h3>

        <p>Artikel</p>
      </div>
      <div class="icon">
        <i class="fas fa-image"></i>
      </div>
      <a href="{{ route('admin.artikel.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-warning">
      <div class="inner">
        <h3>@count('pengumuman')</h3>

        <p>Pengumuman</p>
      </div>
      <div class="icon">
        <i class="fas fa-info"></i>
      </div>
      <a href="{{ route('admin.pengumuman.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-danger">
      <div class="inner">
        <h3>@count('agenda')</h3>

        <p>Agenda</p>
      </div>
      <div class="icon">
        <i class="fas fa-list"></i>
      </div>
      <a href="{{ route('admin.agenda.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <!-- ./col -->
</div>
<!-- /.row -->
@stop

laraschool/resources/views/admin/profile.blade.php
@extends('layouts.backend.app',[
	'title' => 'Profile',
	'contentTitle' => 'Profile',
])
@section('content')
<x-alert></x-alert>
<div class="row">
	<x-card>
		<x-slot name="col">6</x-slot>
		<x-slot name="header">Profil Saya</x-slot>
		<div class="form-group">
			<label>Nama Lengkap</label>
			<input type="" disabled="" value="{{ auth()->user()->name }}" class="form-control" name="">
		</div>
		<div class="form-group">
			<label>Email</label>
			<input type="" disabled="" value="{{ auth()->user()->email }}" class="form-control" name="">
		</div>
	</x-card>

	<x-card>
		<x-slot name="col">6</x-slot>
		<x-slot name="header">Edit Profil</x-slot>
		<form method="POST" action="{{ route('user-profile-information.update') }}">
		@csrf
		@method('put')
		<div class="form-group">
			<label>Nama Lengkap</label>
			<input type="" value="{{ auth()->user()->name }}" class="form-control @error('name') is-invalid @enderror" name="name">
			@error('name')
		      <div class="invalid-feedback">
		          {{ $message }}
		       </div>
		    @enderror
		</div>
		<div class="form-group">
			<label>Email</label>
			<input type="email" value="{{ auth()->user()->email }}" class="form-control @error('email') is-invalid @enderror" name="email">
			@error('email')
		      <div class="invalid-feedback">
		          {{ $message }}
		       </div>
		    @enderror
		</div>
		<div class="form-group">
			<button type="submit" class="btn btn-primary btn-sm">UPDATE</button>
		</div>
		</form>
	</x-card>

</div>
@stop